## Tensor

#### import

In [1]:
import numpy as np
import torch

### concept

- 2D : (batch size, dim)
- 3D 
    - vision : (batch size, width, height)
    - NLP    : (batch size, length, dim)

## Numpy

### 1차원

In [8]:
ar1 = np.array(range(6 + 1), dtype = float)
print(ar1)
print(f"Rank : {ar1.ndim}, Shape : {ar1.shape}")

[0. 1. 2. 3. 4. 5. 6.]
Rank : 1, Shape : (7,)


### 2차원

In [17]:
ar2 = np.array([range(x,x+3) for x in range(1, 10+1, 3)])
print(ar2)
print(f"Rank : {ar2.ndim}, Shape : {ar2.shape}")

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Rank : 2, Shape : (4, 3)


## Torch

### 1차원

In [24]:
ts1 = torch.FloatTensor(range(6 + 1))
print(ts1)
print(f"Rank : {ts1.ndim}, Shape : {ts1.shape}, Size : {ts1.size()}")

tensor([0., 1., 2., 3., 4., 5., 6.])
Rank : 1, Shape : torch.Size([7]), Size : torch.Size([7])


### 2차원

In [27]:
ts2 = torch.FloatTensor([range(x,x+3) for x in range(1, 10+1, 3)])
print(ts2)
print(f"Rank : {ts2.ndim}, Shape : {ts2.shape}, Size : {ts2.size()}")

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
Rank : 2, Shape : torch.Size([4, 3]), Size : torch.Size([4, 3])


### Broadcasting
다른 크기의 행렬들을 더하고 뺄 때 
자동적으로 사이즈를 맞춰 진행

#### 같은 크기

In [29]:
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])
m1 + m2

tensor([[5., 5.]])

#### 다른 크기

In [30]:
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3]])
m1 + m2

tensor([[4., 5.]])

In [31]:
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3],[4]])
m1 + m2

tensor([[4., 5.],
        [5., 6.]])

### Matmul Vs Mul

In [32]:
m1 = torch.FloatTensor([[1,2], [3,4]])
m2 = torch.FloatTensor([[1],[2]])
m1.matmul(m2)

tensor([[3.],
        [7.]])

#### mul은 broadcasting 진행

In [34]:
m1 = torch.FloatTensor([[1,2], [3,4]])
m2 = torch.FloatTensor([[1],[2]])
print(m1.mul(m2))
print(m1 * m2)

tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


### Mean, Sum, Max

In [35]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [36]:
t = torch.LongTensor([1, 2])
try:
    print(t.mean())
except Exception as exc:
    print(exc)

Can only calculate the mean of floating types. Got Long instead.


In [52]:
t = torch.FloatTensor([range(x,x+2) for x in [1, 3]])
print(t.mean())
dim_ls = [0, 1, -1]
print("모든 원소의 합")
print(f"mean : {t.mean()} ,sum : {t.sum()}")
print("dim번째 dim에 대해서 평균(0 : 열, 1 : 행) -> 각 dim이 1차원으로 축소")
for dim in dim_ls:
    max_val  = t.max(dim = dim)[0]
    arg_max  = t.max(dim = dim)[1]
    print(f"dim : {dim} mean : {t.mean(dim = dim)} ,sum : {t.sum(dim = dim)}, max : {max_val}, argmax : {arg_max}")
print("max의 경우 ")

tensor(2.5000)
모든 원소의 합
mean : 2.5 ,sum : 10.0
dim번째 dim에 대해서 평균(0 : 열, 1 : 행) -> 각 dim이 1차원으로 축소
dim : 0 mean : tensor([2., 3.]) ,sum : tensor([4., 6.]), max : tensor([3., 4.]), argmax : tensor([1, 1])
dim : 1 mean : tensor([1.5000, 3.5000]) ,sum : tensor([3., 7.]), max : tensor([2., 4.]), argmax : tensor([1, 1])
dim : -1 mean : tensor([1.5000, 3.5000]) ,sum : tensor([3., 7.]), max : tensor([2., 4.]), argmax : tensor([1, 1])
max의 경우 


## View

In [60]:
t = np.array([[range(x,x+3) for x in [y, y+3]] for y in [0, 6]])
ft = torch.FloatTensor(t)

In [63]:
print(ft)
print(ft.shape)

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])
torch.Size([2, 2, 3])


In [64]:
ft2 = ft.view([-1, 3])
print(ft2)
print(ft2.shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [65]:
ft3 = ft.view([-1, 1, 3])
print(ft3)
print(ft3.shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


### Squeeze

In [68]:
ft = torch.FloatTensor([[x] for x in range(2 + 1)])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [72]:
ft_s = ft.squeeze(dim = 1)
print(ft_s)
print(ft_s.shape)

tensor([0., 1., 2.])
torch.Size([3])


### Unsqueeze

In [74]:
ft = torch.FloatTensor(range(2 + 1))
print(ft)
print(ft.shape)

tensor([0., 1., 2.])
torch.Size([3])


In [75]:
ft_us = ft.unsqueeze(0)
print(ft_us)
print(ft_us.shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


### Concatenate

In [78]:
x = torch.FloatTensor([[x,x+1] for x in [1, 3]])
y = torch.FloatTensor([[x,x+1] for x in [5, 7 ]])

In [81]:
print(torch.cat([x,y], dim = 0)) ## 열 방향
print(torch.cat([x,y], dim = 1)) ## 행 방향

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


### Stacking

In [82]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [88]:
x

tensor([1., 4.])

In [85]:
print(torch.stack([x, y, z]))
print(torch.stack([x, y, z], dim = 1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


### stack과 cat의 차이
-> 차원을 하나 늘려서 더해줌

In [89]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


### Inplace Operation
_를 붙이면 inplace 됨